version: '3'

services:
  db:
    image: postgres:10.1-alpine
    ports:
      - "54320:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      ports:
          - "5672:5672"
  web:
    build: .
    command: sh ./web_init.sh
    volumes:
      - .:/gog
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=h8z#!iqe5976#l%)xk_f#$r37+hg!*oz-!t2ipk!(#nzx45*z
  worker:
    build: .
    command: celery -A google_scraper worker -l info
    volumes:
      - .:/gog
    depends_on:
      - rabbit
    environment:
      - DJANGO_SECRET_KEY=h8z#!iqe5976#l%)xk_f#$r37+hg!*oz-!t2ipk!(#nzx45*z
  selenium-chrome:
    hostname: selenium-chrome
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900
  selenium-firefox:
    hostname: selenium-firefox
    image: selenium/standalone-firefox-debug:3.7.1
    ports:
      - 4445:4444
      - 5901:5900
volumes:
  postgres_data: