# Generated by Django 2.2.2 on 2019-07-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('text', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('popular_words', models.TextField()),
                ('num_results', models.PositiveIntegerField()),
                ('client_ip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('qu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.Query')),
            ],
        ),
    ]
