# Generated by Django 2.2.3 on 2019-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20190707_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='browser',
            field=models.TextField(default='no info'),
            preserve_default=False,
        ),
    ]
